### ISSUE TITLE
Support text detection

### ISSUE THREAD

**Issue by huningxin** [WICG/shape-detection-api#6]
### iOS

[CITextFeature](https://developer.apple.com/library/ios/documentation/CoreImage/Reference/CITextFeature_Class/index.html#//apple_ref/occ/cl/CITextFeature): only supports bounding box
### Android

[com.google.android.gms.vision.text.TextRecognizer](https://developers.google.com/android/reference/com/google/android/gms/vision/text/TextRecognizer): supports OCR

**Comment by miguelao** [comment]
Another: Windows10
https://msdn.microsoft.com/en-us/library/windows/apps/windows.media.ocr.aspx

**Comment by yellowdoge** [comment]
Scrubbing this issue since Text Detection is already [in the Spec](https://wicg.github.io/shape-detection-api/#text-detection-api) and is implemented in Chrome for [Android](https://chromium.googlesource.com/chromium/src.git/+/lkgr/services/shape_detection/android/java/src/org/chromium/shape_detection/TextDetectionImpl.java) and [Mac](https://chromium.googlesource.com/chromium/src.git/+/lkgr/services/shape_detection/text_detection_impl_mac.h).
