### ISSUE TITLE
QR/Barcode	on Windows 10

### ISSUE THREAD

**Issue by StefanFeederle** [WICG/shape-detection-api#67]
Barcode detection on Windows 10 is currently unsupported. Is there anything planned?

**Comment by tomayac** [comment]
The problem is that Windows doesn’t have support for barcode scanning on the system level: https://github.com/WICG/shape-detection-api/blob/master/README.md#windows. I guess your best bet right now is to go with a [wasm port of ZXing](https://www.codepool.biz/building-webassembly-zxing-windows.html).

**Comment by reillyeon** [comment]
Closing this issue. Whether or not to support barcode detection on Windows 10 is up to each implementation, not the specification.
